### ISSUE TITLE
I can not use

### ISSUE THREAD

**Issue by mostafa0050** [qingshan/mdict_reader#2]
Hello, how can I use your code to get the output from the .mdx file?
My file name is camb.mdx and I execute your code like this and this output is displayed.
please help me.

`dart bin/main.dart defintion camb.mdx "book"`

output :
```
Unhandled exception:
FormatException: Unexpected extension byte (at offset 1)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1788:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
#2      BytesInputStream.readString (package:mdict_reader/src/input_stream.dart:187:33)
#3      MdictReader._read_keys (package:mdict_reader/src/mdict_reader_base.dart:93:33)
#4      new MdictReader (package:mdict_reader/src/mdict_reader_base.dart:31:17)
#5      main (file:///media/mdict_reader-master/bin/main.dart:11:15)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by qingshan** [comment]
Please check the `Encoding` field in headers in your .mdx file, it must be `UTF-8`, not `utf-8`.
