### ISSUE TITLE
Index out of range: no indices are valid: 0

### ISSUE THREAD

**Issue by winterdl** [qingshan/mdict_reader#4]
```
void main(List<String> args) {
  var parser = ArgParser();
  var results = parser.parse(args);

  var path = results.rest[0];
  var word = results.rest[1];

  var mdict = MdictReader(path);
  var result = mdict.query('agley');

  print(result);
}
```

dict files: 

[dict.zip](https://github.com/qingshan/mdict_reader/files/11084803/dict.zip)

with this error message:

```
RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:3118:7)
#1      MdictReader._decompressBlock (package:mdict_reader/src/mdict_reader_base.dart:185:25)
#2      MdictReader._readRecord (package:mdict_reader/src/mdict_reader_base.dart:168:19)
#3      MdictReader.query.<anonymous closure> (package:mdict_reader/src/mdict_reader_base.dart:50:23)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#7      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#8      new List.of (dart:core-patch/array_patch.dart:52:28)
#9      ListIterable.toList (dart:_internal/iterable.dart:214:7)
#10     MdictReader.query (package:mdict_reader/src/mdict_reader_base.dart:51:10)
#11     main (file:///Users/admin/Downloads/mdict_reader-master1/mdict_reader-master/bin/test.dart:12:19)
#12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

`the exception occur in _readRecord functions, the print('compress size $compressedSize'); always return 0.`

**Comment by gsy13213009** [comment]
this library can't be use
